language: node_js

node_js:
  - 0.10
  - 0.12
  - 4.4
  - 5.8
matrix:
    allow_failures:
        - node_js: 4.4
        - node_js: 5.8

install:
 - npm install

before_script:
 - npm install npm

script:
 - npm test
